branch-defaults:
  default:
    environment: codeCastServer-prod
global:
  application_name: codeCastServer
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: shupe
  repository: null
  sc: null
  workspace_type: Application
